acquavel/acquavel/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include(admin.site.urls)),
    url(r'^api/', include('socios.urls')),
    url(r'^api/', include('actividades.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

acquavel/actividades/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = patterns('',
   url(r'^actividades/', views.ClaseList.as_view())
)

urlpatterns = format_suffix_patterns(urlpatterns)

acquavel/socios/urls.py
from django.conf.urls import patterns, include, url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = patterns('',
   url(r'^socio/(?P<pk>[0-9]+)/$', views.SocioDetail.as_view(), name='socio_detail')
)

urlpatterns = format_suffix_patterns(urlpatterns)

acquavel/actividades/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext as _


class DiaHorario(models.Model):
    DIA_LUNES = 0
    DIA_MARTES = 1
    DIA_MIERCOLES = 2
    DIA_JUEVES = 3
    DIA_VIERNES = 4
    DIA_SABADO = 5
    DIA_DOMINGO = 6

    DIAS_OPCIONES = (
        (DIA_LUNES, _(u'Lunes')),
        (DIA_MARTES, _(u'Martes')),
        (DIA_MIERCOLES, _(u'Miercoles')),
        (DIA_JUEVES, _(u'Jueves')),
        (DIA_VIERNES, _(u'Viernes')),
        (DIA_SABADO, _(u'Sabado')),
        (DIA_DOMINGO, _(u'Domingo')),
    )
    dia = models.PositiveSmallIntegerField(choices=DIAS_OPCIONES, verbose_name=_(u'Día'))
    desdehora = models.TimeField()
    hastahora = models.TimeField()

    def __unicode__(self):
        return u'{}, {} - {}'.format(self.get_dia_display(), self.desdehora, self.hastahora)

    class Meta:
        unique_together = (("dia", "desdehora", "hastahora"),)
        ordering = ['dia', 'desdehora']


class Clase(models.Model):
    descripcion = models.CharField(max_length=200)
    horarios = models.ManyToManyField(DiaHorario)

    def __unicode__(self):
        return self.descripcion

acquavel/socios/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Plan(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    descripcion = models.CharField(max_length=200)
    cant_clases = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = u'Planes'

    def __unicode__(self):
        return self.descripcion


class Socio(models.Model):
    dni = models.PositiveIntegerField(primary_key=True)
    planes = models.ManyToManyField(Plan, through='Contratacion')
    rev_medica = models.DateField(blank=True, null=True, verbose_name=u'Revisación médica')

    def __unicode__(self):
        return str(self.dni)


class Contratacion(models.Model):
    plan = models.ForeignKey(Plan)
    socio = models.ForeignKey(Socio)
    inicio = models.DateField()
    final = models.DateField()

    class Meta:
        verbose_name_plural = u'Contrataciones'

    def __unicode__(self):
        return u'{} - {} - {} - {}'.format(self.socio, self.plan, self.inicio, self.final)


class Ingreso(models.Model):
    contratacion = models.ForeignKey(Contratacion)
    fecha = models.DateField()

    def __unicode__(self):
        return u'{} - {}'.format(self.contratacion, self.fecha)

acquavel/actividades/views.py
from rest_framework import generics
from .serializers import ClaseSerializer
from models import Clase


class ClaseList(generics.ListAPIView):
    queryset = Clase.objects.all()
    serializer_class = ClaseSerializer

acquavel/socios/views.py
from rest_framework import generics
from .serializers import SocioSerializer
from models import Socio, Ingreso
from django.views.generic.edit import CreateView


class SocioDetail(generics.RetrieveAPIView):
    queryset = Socio.objects.all()
    serializer_class = SocioSerializer


class IngresoView(CreateView):
    model = Ingreso
    fields = ['contratacion','fecha']
    success_url = '/admin/'

    def get_context_data(self, **kwargs):
        context = super(IngresoView, self).get_context_data(**kwargs)
        context['opts'] = self.model._meta
        context['add'] = True
        context['original'] = self.object
        context['has_change_permission'] = self.request.user.has_perm("socios.add")
        return context

acquavel/templates/socios/ingreso_form.html
{% extends "admin/change_form.html" %}
{% load i18n %}
{% block extrahead %}{{ block.super }}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script type="text/javascript">
    (function($) {
            $(document).ready(function() {
                var timeout, timeout2;
                var contrataciones_list = [];
                var today = new Date();
                var yesterday = new Date();
                yesterday.setDate(yesterday.getDate() - 1);
                today.day = today.getDate();
                today.month = today.getMonth() + 1;
                today.year = today.getFullYear();
                yesterday.day = yesterday.getDate();
                yesterday.month = yesterday.getMonth() + 1;
                yesterday.year = yesterday.getFullYear();

                $(document).find("#id_contratacion").parent().append('<div id="prefilter_div"><input type="text" id="prefilter"></div>');
                $(document).find("#prefilter_div").append('<ul id="prefilterList"></ul>');
                $(document).find("#id_contratacion").hide();
                $(document).find("#id_fecha").attr('placeholder', 'YYYY-MM-DD');
                $(document).find("#id_fecha").parent().append('<div id="quick_day"><span id="today">Hoy</span><span id="yesterday">Ayer</span></div>');


                $(document).find('#quick_day').on('click', 'span', function (){
                    if ($(this).prop('id') === "today") {
                        $(document).find("#id_fecha").val(today.year + '-' + today.month + '-' + today.day);
                    } else {
                        $(document).find("#id_fecha").val(yesterday.year + '-' + yesterday.month + '-' + yesterday.day);
                    }
                });

                $(document).find("#id_contratacion option").each(function(){
                    //console.log($(this).attr("value"));
                    if ($(this).attr("value") != "") {
                        var element = {"value": $(this).attr("value"),
                            "dni": $.trim($(this).html().split("-")[0]),
                            "string": $(this).html()};
                        contrataciones_list.push(element);
                    }
                });

                $(document).find("#prefilter").keyup(function() {
                    clearTimeout(timeout);
                    timeout = setTimeout(loadList, 1000);
                });

                $(document).find("#prefilterList").on('click', 'li', function (){
                    clearTimeout(timeout2);
                    var value = $(this).attr("value");
                    var dni = $.trim($(this).html().split("-")[0]);
                    $(document).find("option[value="+value+"]").prop('selected',true);
                    $(document).find("#prefilter").val(dni);
                    $(document).find("#prefilterList").hide();
                    console.log("clicked");
                });

                $(document).find("#prefilter").focusin(function (){
                    clearTimeout(timeout2);
                    if ($(document).find("#prefilterList li").length != 0){
                        $(document).find("#prefilterList").show();
                        console.log("show");
                    }
                });

                $(document).find("#prefilter").focusout(function (){
                    clearTimeout(timeout2);
                    timeout2 = setTimeout(function (){
                        $(document).find("#prefilterList").hide();
                        console.log("hide");
                    }, 500);
                });

                function loadList(){
                    $(document).find("#prefilterList").html('');
                    var arg = $(document).find("#prefilter").val();
                    if ($.trim(arg).length != 0) {
                        $.each(contrataciones_list, function (key, val){
                            if (val.dni.indexOf(arg) >= 0) {
                                var li = '<li value="'+val.value+'">'+val.string+'</li>';
                                $(document).find("#prefilterList").append(li);
                            }
                        });
                        if ($(document).find("#prefilterList li").length != 0){
                            $(document).find("#prefilterList").show();
                        } else {
                            $(document).find("#prefilterList").hide();
                        }
                    } else {
                        $(document).find("#prefilterList").hide();
                    }
                }
            });
    })(jQuery);
</script>
<style>
    #prefilter_div {
        position: relative;
        display: inline-block;
    }
    #prefilterList {
        position: absolute;
        margin: 0px;
        width: auto;
        padding: 0;
        max-height: 200px;
        overflow-y: scroll;
        border: 1px solid grey;
        background: white;
        display: none;
    }
    #prefilterList li {
        position: relative;
        float: left;
        width: 100%;
        list-style: outside none none;
        white-space: nowrap;
        padding: 1px 0;
    }
    #prefilterList li:hover {
        background-color: #F0F0F0;
        cursor: pointer;
    }
    form p label {
        width: 85px;
        position: relative;
        display: inline-block;
    }
    form p input {
        text-align: center;
    }
    #quick_day {
        position: relative;
        display: inline-block;
    }
    #quick_day span {
        color: #5B80B2;
        text-decoration: none;
        margin: 0 0 0 15px;
    }
    #quick_day span:hover {
        color: #036;
        cursor: pointer;
    }
</style>
{{ media }}
{% endblock %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Crear" />
</form>
{% endblock %}